plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag

permalink: pretty

collections:
  gallery:
    output: true
    permalink: /:collection/:categories/:title
  projects:
    output: true
    permalink: /project/:title
  posts:
    output: true
    permalink: /:collection/:categories/:year/:month/:day/:title

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "gallery"
    values:
      layout: "image"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "regular"
