plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag

permalink: pretty

collections:
  art_images:
    output: true
    permalink: /:collection/:title
  projects:
    output: true
    permalink: /project/:title
  posts:
    output: true
    permalink: /:collection/:categories/:year/:month/:day/:title

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "regular"
  - scope:
      path: ""
      type: "art_images"
    values:
      layout: "images"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "regular"
